WebTakenApp/Controllers/GroepController.cs
using BusnLogicTakenApp;
using DALMemoryStore;
using DALMemoryStore.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using WebTakenApp.Models;

namespace WebTakenApp.Controllers
{
    public class GroepController : Controller
    {
        GroepContainer groepContainer = new GroepContainer(new GroepDAL());
        TaakContainer taakContainer = new TaakContainer(new TaakDAL());
        PersoonContainer persoonContainer = new PersoonContainer(new PersoonDAL());
        ProjectContainer projectContainer = new ProjectContainer(new ProjectDAL());
        public IActionResult Index()
        {
            try
            {
                int id = Convert.ToInt32(HttpContext.Session.GetString("PersoonId"));
                if (id != 0)
                {
                    dynamic mymodel = new ExpandoObject();
                    mymodel.GroepVM = GetGroepVMs(id);
                    mymodel.TaakVM = GetTaakVMs(id);
                    return View(mymodel);
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                GroepVM groepVM = new GroepVM();
                return PartialView("_GroepModelPartial", groepVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Create(GroepVM groepVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = Convert.ToInt32(HttpContext.Session.GetString("PersoonId"));
                    Persoon persoon = persoonContainer.FindById(id);
                    Groep groep = groepContainer.Create(groepVM.GetGroep());
                    groep.Project = groepVM.project.GetProject();
                    groep.Project.GroepId = groep.Id;
                    projectContainer.Create(groep.Project);
                    groepContainer.VoegPersoonAanGroep(groep.Id, persoon.Gebruikersnaam);
                    return PartialView("_GroepModelPartial", groepVM);
                }
                return View(groepVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }

        }
        //TODO: fixen
        [HttpPost]
        public IActionResult VoegGroepslidToe(int groepId, string gebruikersnaam)
        {
            try
            {
                if (groepId != null && gebruikersnaam != null)
                {
                    groepContainer.VoegPersoonAanGroep(groepId, gebruikersnaam);
                }
                return RedirectToAction("Index");
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }
        private List<GroepVM> GetGroepVMs(int persoonId)
        {
            try
            {
                List<Groep> groepen = groepContainer.FindByPersoon(persoonId);
                List<GroepVM> groepViewModels = groepen.ConvertAll(x => new GroepVM(x));
                return groepViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
        private List<TaakVM> GetTaakVMs(int persoonId)
        {
            try
            {
                List<Taak> taken = taakContainer.FindByPersoon(persoonId);
                List<TaakVM> taakViewModels = taken.ConvertAll(x => new TaakVM(x));
                return taakViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
    }
}

WebTakenApp/Controllers/RegisterController.cs
using BusnLogicTakenApp;
using DALMemoryStore;
using Microsoft.AspNetCore.Mvc;
using WebTakenApp.Models;
using System.Data;
using DALMemoryStore.Exceptions;

namespace WebTakenApp.Controllers
{
    public class RegisterController : Controller
    {
        PersoonContainer persoonContainer = new PersoonContainer(new PersoonDAL());
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PersoonVM persoon)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Persoon user = persoon.GetPersoon();
                    persoonContainer.Create(user, persoon.Wachtwoord);
                    ViewBag.Message = "Gebruiker is aangemaakt";
                    return RedirectToAction("Index", "Login");
                }
                return View(persoon);
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
    }
}

WebTakenApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebTakenApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebTakenApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-star-rating@4.1.2/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-info bg-info">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Groep" asp-action="Index">Zrello</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("PersoonId") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Groep" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Create">Register</a>
                            </li>
                            
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebTakenApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>