WebTakenApp/Controllers/GroepController.cs
using BusnLogicTakenApp;
using DALMemoryStore;
using DALMemoryStore.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using WebTakenApp.Models;

namespace WebTakenApp.Controllers
{
    public class GroepController : Controller
    {
        GroepContainer groepContainer = new GroepContainer(new GroepDAL());
        TaakContainer taakContainer = new TaakContainer(new TaakDAL());
        PersoonContainer persoonContainer = new PersoonContainer(new PersoonDAL());
        ProjectContainer projectContainer = new ProjectContainer(new ProjectDAL());
        public IActionResult Index()
        {
            try
            {
                int id = Convert.ToInt32(HttpContext.Session.GetString("PersoonId"));
                if (id != 0)
                {
                    dynamic mymodel = new ExpandoObject();
                    mymodel.GroepVM = GetGroepVMs(id);
                    mymodel.TaakVM = GetTaakVMs(id);
                    return View(mymodel);
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                GroepVM groepVM = new GroepVM();
                return PartialView("_GroepModelPartial", groepVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Create(GroepVM groepVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = Convert.ToInt32(HttpContext.Session.GetString("PersoonId"));
                    Persoon persoon = persoonContainer.FindById(id);
                    Groep groep = groepContainer.Create(groepVM.GetGroep());
                    groep.Project = groepVM.project.GetProject();
                    groep.Project.GroepId = groep.Id;
                    projectContainer.Create(groep.Project);
                    groepContainer.VoegPersoonAanGroep(groep.Id, persoon.Gebruikersnaam);
                    return PartialView("_GroepModelPartial", groepVM);
                }
                return View(groepVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }

        }
        //TODO: fixen
        [HttpPost]
        public IActionResult VoegGroepslidToe(int groepId, string gebruikersnaam)
        {
            try
            {
                if (groepId != null && gebruikersnaam != null)
                {
                    groepContainer.VoegPersoonAanGroep(groepId, gebruikersnaam);
                }
                return RedirectToAction("Index");
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }
        private List<GroepVM> GetGroepVMs(int persoonId)
        {
            try
            {
                List<Groep> groepen = groepContainer.FindByPersoon(persoonId);
                List<GroepVM> groepViewModels = groepen.ConvertAll(x => new GroepVM(x));
                return groepViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
        private List<TaakVM> GetTaakVMs(int persoonId)
        {
            try
            {
                List<Taak> taken = taakContainer.FindByPersoon(persoonId);
                List<TaakVM> taakViewModels = taken.ConvertAll(x => new TaakVM(x));
                return taakViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
    }
}

WebTakenApp/Controllers/TaakController.cs
using BusnLogicTakenApp;
using DALMemoryStore;
using DALMemoryStore.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using WebTakenApp.Models;

namespace WebTakenApp.Controllers
{
    public class TaakController : Controller
    {
        GroepContainer groepContainer = new GroepContainer(new GroepDAL());
        TaakContainer taakContainer = new TaakContainer(new TaakDAL());
        public IActionResult Index(int groepId, int persoonId)
        {
            try
            {
                int id = Convert.ToInt32(HttpContext.Session.GetString("PersoonId"));
                if (id != 0)
                {
                    TempData["groepId"] = groepId;
                    TempData["persoonId"] = persoonId;
                    TempData.Keep();
                    dynamic mymodel = new ExpandoObject();
                    mymodel.GroepVM = GetGroepVMs(id);
                    mymodel.TaakVM = GetTaakVMs(groepId, persoonId);
                    return View(mymodel);
                }
                else
                {
                    return RedirectToAction("Index", "Login");
                }
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            TaakVM taakVM = new TaakVM();
            return PartialView("_TaakModelPartial", taakVM);
        }

        [HttpPost]
        public IActionResult Create(TaakVM taakVM)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    int groepId = Convert.ToInt32(TempData["groepId"]);
                    int persoonId = Convert.ToInt32(TempData["persoonId"]);
                    taakVM.GroepId = groepId;
                    taakVM.PersoonId = persoonId;
                    Taak taak = taakVM.GetTaak();
                    taakContainer.Create(taak);
                    ViewBag.Message = "Taak is toegevoegd";
                    return PartialView("_TaakModelPartial", taakVM);
                }
                return View(taakVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }

        }
        
        [HttpGet]
        public IActionResult Update(int taakId)
        {
            try
            {
                Taak taak = taakContainer.FindById(taakId);
                TaakVM taakVM = new TaakVM(taak);
                return PartialView("_EditTaakModelPartial", taakVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Update(TaakVM taakVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Taak taak = taakVM.GetTaak();
                    taakContainer.Update(taak);
                    ViewBag.Message = "Taak is Updated";
                    return PartialView("_EditTaakModelPartial", taakVM);
                }
                return View(taakVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }

        }
        [HttpGet]
        public IActionResult Delete(int taakId)
        {
            try
            {
                Taak taak = taakContainer.FindById(taakId);
                TaakVM taakVM = new TaakVM(taak);
                return PartialView("_DeleteTaakModelPartial", taakVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult Delete(TaakVM taakVM)
        {
            try
            {
                Taak taak = taakVM.GetTaak();
                taakContainer.Delete(taak.Id);
                ViewBag.Message = "Taak is verwijderd";
                return PartialView("_DeleteTaakModelPartial", taakVM);
            }
            catch (TemporaryDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
            catch (PermanentDalException ex)
            {
                ViewBag.Message = ex.Message;
                return Content(ex.Message);
            }
        }

        private List<GroepVM> GetGroepVMs(int persoonId)
        {
            try
            {
                List<Groep> groepen = groepContainer.FindByPersoon(persoonId);
                List<GroepVM> groepViewModels = groepen.ConvertAll(x => new GroepVM(x));
                return groepViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
        private List<TaakVM> GetTaakVMs(int groepId, int persoonId)
        {
            try
            {
                List<Taak> taken = taakContainer.FindByPersoonInGroep(groepId, persoonId);
                List<TaakVM> taakViewModels = taken.ConvertAll(x => new TaakVM(x));
                return taakViewModels;
            }
            catch (TemporaryDalException)
            {
                throw new TemporaryDalException($"Check uw verbinding");
            }
            catch (PermanentDalException)
            {
                throw new TemporaryDalException($"Er is iets fout gegaan");
            }
        }
    }
}

WebTakenApp/Views/Groep/Index.cshtml
@using System.Security.Policy
@using WebTakenApp.Models
@model dynamic
@{
    ViewData["Title"] = "Index";
}

<div id="PlaceHolderHere"></div>
<div class="sidenav">
    <h6>Mijn Groepen</h6> <br />
    @foreach (var groep in Model.GroepVM)
    {
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">@groep.Naam</a>
        <ul class="dropdown-menu">
            @foreach (var persoon in groep.personen)
            {
                <li><a class="dropdown-item" href="@Url.Action("Index","Taak", new { groepId = groep.Id, persoonId = persoon.Id})">@persoon.Naam</a></li>
            }
            <li>
                <form id="myForm" action="/Groep/VoegGroepslidToe" method="Post">
                    <input type="hidden" name="groepId" value="@groep.Id" />
                    <div class="form-floating small">
                        <input type="text" class="form-control" id="floatingInput" placeholder="Gebruikersnaam">
                        <label for="floatingInput">Gebruikersnaam</label>
                    </div>
                    <button type="submit">Toevoegen</button>
                </form>
            </li>
        </ul>
    }
    <button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#groepToevoegen" data-url="@Url.Action("Create","Groep")">
        Nieuwe groep maken
    </button>

</div>
<div class="main">
    <div class="container">

        <table class="table table-striped table-hover" style="width:100%">
            <thead>
                <tr>
                    <th scope="col">Naam</th>
                    <th scope="col">Beschrijving</th>
                    <th scope="col">Deadline</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var taak in Model.TaakVM)
                {
                    int id = taak.Id;
                    <tr>
                        <td>
                            <a href="@Url.Action("Index","Taak", new { groepId = taak.GroepId, persoonId = taak.PersoonId})">
                                @taak.Naam
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Index","Taak", new { groepId = taak.GroepId, persoonId = taak.PersoonId})">
                                @taak.Beschrijving
                            </a>
                        </td>
                        <td>
                            <a href="@Url.Action("Index","Taak", new { groepId = taak.GroepId, persoonId = taak.PersoonId})">
                                @taak.Deadline
                            </a>
                        </td>
                        <td>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WebTakenApp/Views/Groep/_GroepModelPartial.cshtml
@model GroepVM

<!-- Modal -->
<div class="modal fade" id="groepToevoegen" tabindex="-1" aria-labelledby="groepToevoegenLabel" aria-hidden="true">
    <div class=" modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="groepToevoegenLabel">Nieuw Groep</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="Create">
                    <div class="form-group">
                        <label asp-for="Naam">Naam</label>
                        <input asp-for="Naam" class="form-control">
                        <span asp-validation-for="Naam" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="project.Naam">Projectnaam</label>
                        <input asp-for="project.Naam" class="form-control">
                        <span asp-validation-for="project.Naam" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="project.Beschrijving">Projectbeschrijving</label>
                        <input asp-for="project.Beschrijving" class="form-control">                         
                        <span asp-validation-for="project.Beschrijving" class="text-danger"></span>
                    </div>
                    <br />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Annuleren</button>
                <button type="button" class="btn btn-primary" data-save="modal" data-url="@Url.Action("Create","Groep")">Groep maken</button>
            </div>
        </div>
    </div>
</div>